FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY data ./data
COPY not_interesting ./not_interesting
COPY mongo ./mongo


CMD ["uvicorn", "not_interesting.consumer_not_interesting_api:app", "--host", "0.0.0.0", "--port", "8002"]
